# Generated by Django 4.2.6 on 2023-12-09 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['-date_added'], 'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='consultant',
            options={'ordering': ('-date_joined',)},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ('-date_joined',)},
        ),
        migrations.AlterModelOptions(
            name='newuser',
            options={'ordering': ('-date_joined',)},
        ),
    ]
