# Generated by Django 4.2.6 on 2023-11-05 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='state',
            field=models.CharField(max_length=100, verbose_name='Pays'),
        ),
    ]
