# Generated by Django 4.2.6 on 2023-11-16 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('store', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItemStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'En attente'), ('PR', 'En traitement'), ('S', 'Expédié'), ('D', 'Livré'), ('R', 'Retourné')], max_length=2, verbose_name='Nouveau statut de la commande')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Commentaire sur la modification')),
                ('date_modified', models.DateTimeField(auto_now_add=True, verbose_name='Date de modification')),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.consultant', verbose_name='Consultant')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer', verbose_name='Client')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.orderitem', verbose_name='Article de commande')),
            ],
        ),
    ]
