# Generated by Django 4.2.6 on 2023-11-09 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_shippingaddress_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='customer',
            new_name='user',
        ),
    ]
