# Generated by Django 4.2.6 on 2023-11-16 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_orderitemstatushistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ('-date_added',)},
        ),
    ]
