# Generated by Django 4.2.6 on 2023-11-11 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_orderitem_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
