# Generated by Django 4.2.6 on 2023-11-15 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_product_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('P', 'En attente'), ('PR', 'En traitement'), ('S', 'Expédié'), ('D', 'Livré'), ('R', 'Retourné')], default='P', max_length=2, verbose_name='Statut de la commande'),
        ),
    ]
