# Generated by Django 4.2.6 on 2023-11-15 18:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_orderitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_ordered',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name="Date d'ajout"),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name="Date d'ajout"),
        ),
    ]
