# Generated by Django 4.2.6 on 2023-11-15 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_orderitem_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date_ordered',
        ),
    ]
