# Generated by Django 4.2.6 on 2023-11-01 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messagerie', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='threadmodel',
            old_name='user',
            new_name='sender',
        ),
    ]
