# Generated by Django 4.2.6 on 2023-11-01 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messagerie', '0002_rename_user_threadmodel_sender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='threadmodel',
            old_name='sender',
            new_name='user',
        ),
    ]
