# Generated by Django 4.2.6 on 2023-11-01 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messagerie', '0004_alter_messagemodel_thread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemodel',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='messagerie.threadmodel'),
        ),
    ]
