# Generated by Django 4.2.6 on 2023-12-27 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_address_options_alter_consultant_options_and_more'),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiMessageWrittenByCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='users.consultant')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='users.customer')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
